"""Added indexes

Revision ID: b0caf9cdaa53
Revises: ff9d78deef76
Create Date: 2025-10-08 16:38:55.893048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0caf9cdaa53'
down_revision: Union[str, None] = 'ff9d78deef76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_approved_guest_requests_status_active', 'approved_guest_requests', ['status'], unique=False)
    op.create_index('idx_guest_borrowed_item', 'approved_guest_requests', ['guest_id', 'item_id'], unique=True, postgresql_where=sa.text('"status" = \'approved\' AND "returned_at" IS NULL'))
    op.create_index('idx_user_borrowed_item', 'user_requests', ['user_id', 'item_id'], unique=True, postgresql_where=sa.text('"status" = \'approved\' AND "returned_at" IS NULL'))
    op.create_index('idx_user_requests_status_active', 'user_requests', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_requests_status_active', table_name='user_requests')
    op.drop_index('idx_user_borrowed_item', table_name='user_requests', postgresql_where=sa.text('"status" = \'approved\' AND "returned_at" IS NULL'))
    op.drop_index('idx_guest_borrowed_item', table_name='approved_guest_requests', postgresql_where=sa.text('"status" = \'approved\' AND "returned_at" IS NULL'))
    op.drop_index('idx_approved_guest_requests_status_active', table_name='approved_guest_requests')
    # ### end Alembic commands ###
